// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7FOe-bmmg1E1QZhmsWx3soHTHd7anJY',
    appId: '1:128784053347:web:e2fa64d480bfeb0556f456',
    messagingSenderId: '128784053347',
    projectId: 'sl-gk-7c93b',
    authDomain: 'sl-gk-7c93b.firebaseapp.com',
    storageBucket: 'sl-gk-7c93b.firebasestorage.app',
    measurementId: 'G-KMEZNDB9K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO6mFrjD-ghbxV6tIFCfhVYCk3ivoC_p4',
    appId: '1:128784053347:android:50b9de1001d238ed56f456',
    messagingSenderId: '128784053347',
    projectId: 'sl-gk-7c93b',
    storageBucket: 'sl-gk-7c93b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvej_RbtPKszs9RldxgAlV-lYEibH3U38',
    appId: '1:128784053347:ios:b22a18c23e6045d956f456',
    messagingSenderId: '128784053347',
    projectId: 'sl-gk-7c93b',
    storageBucket: 'sl-gk-7c93b.firebasestorage.app',
    iosBundleId: 'com.example.gkQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvej_RbtPKszs9RldxgAlV-lYEibH3U38',
    appId: '1:128784053347:ios:b22a18c23e6045d956f456',
    messagingSenderId: '128784053347',
    projectId: 'sl-gk-7c93b',
    storageBucket: 'sl-gk-7c93b.firebasestorage.app',
    iosBundleId: 'com.example.gkQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW7FOe-bmmg1E1QZhmsWx3soHTHd7anJY',
    appId: '1:128784053347:web:0ab65b5fd1ee442f56f456',
    messagingSenderId: '128784053347',
    projectId: 'sl-gk-7c93b',
    authDomain: 'sl-gk-7c93b.firebaseapp.com',
    storageBucket: 'sl-gk-7c93b.firebasestorage.app',
    measurementId: 'G-2T77ET2DVD',
  );

}